name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # დააყენე ზუსტად ის პაკეტები, რაც გვჭირდება აგებისთვის
      - name: Install Android packages
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools" "cmdline-tools;latest"
          yes | sdkmanager --licenses

      # დაგვაყენებინე Gradle გლობალურად (wrapper-ის გარეშე)
      - name: Provision Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Xmx4g
      JAVA_TOOL_OPTIONS: -Xmx4g

      - name: Build debug APK
        run: |
          gradle --version
          gradle :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BirtvisiBridge-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
